package brjt23.chs.wumpus.board;

import org.junit.Assert;
import org.junit.Test;

/**
 * Class that test the Position functionalities.
 * Tests the most important method
 * (Equals has been autogenerated that's why it is not been tested):
 * - Sum: used to move around the board 
 * @author Borja
 *
 */
public class PositionTest {

	
	/**
	 * Test that the result of P(x,y) + Q(1,1) = PQ(x+1,y+1)
	 * and P(x < 0,y = 0) +  Q(0,-1) = PQ(x, y -1) 
	 */
	@Test
	public void sumTest() {
		Position p = new Position(0,0);
		Position q = new Position(1,1);
		
		Assert.assertEquals(q, p.sum(q));
		Assert.assertEquals(new Position(0,-2), p.sum(new Position(0,-2)));
		
	}
}
